### ISSUE TITLE
External link

### ISSUE THREAD

**Issue by lexislav** [dutchheight/craft-navie#10]
Would be cool if external url could be entered as well. Not only internal links.

It is easy to do so with custom fields, but handling this with plugin would keep templates much cleaner :-)

**Comment by freimutt** [comment]
You can change the link type to URL in right side panel. There you can use external urls.

![image](https://user-images.githubusercontent.com/11332285/80471441-b58dba80-8943-11ea-9a25-4229ff211c50.png)

**Comment by lexislav** [comment]
Thanks for pointng out and sorry I haven’t find myself.
