### ISSUE TITLE
Deprecated calls to enabledForSite

### ISSUE THREAD

**Issue by rob-c-baker** [dutchheight/craft-navie#11]
Navie triggers a deprecation warning:

Message: `The enabledForSite element query param has been deprecated. status() should be used instead.`

Origin: `[...project dir...]/vendor/dutchheight/craft-navie/src/services/ListService.php:417`

It looks like swapping that line 417 for something like: `->status(ListItem::STATUS_ENABLED)` would work.

Craft Version: 3.5.11.1
Navie version: 1.2.3

**Comment by verbeeksteven** [comment]
@KevinBeckers @rob-baker-ar this is still an issue with the newest version. Was this fixed?

**Comment by verbeeksteven** [comment]
Looks like 1.2.4 has not been released yet, I'm using dev-master for now.

**Comment by rob-c-baker** [comment]
Not released yet - looks like forcing dev-master in composer.json will work for now.
