### ISSUE TITLE
graphql retreiving menu's

### ISSUE THREAD

**Issue by studiocodeur** [dutchheight/craft-navie#12]
Wanneer ik de voorbeeld query run met mijn eigen lijst naam krijg ik alles terug ipv alleen de lijst die ik wil zien.
 
```
{
  listItems(list: "mijnlijst", level: 1) {
    id,
    title,
    url,
    target,
    children {
      id,
      url,
      title,
      target,
      ... on main_List { # Main is list handle
        classes
      }
    }
  }
}
```

Ik krijg dan alle menu's te zien die ik heb aangemaakt.

**Comment by KevinBeckers** [comment]
Hi, ik ga er even induiken!

**Comment by KevinBeckers** [comment]
Ik heb het een en ander getest en het lijkt er op dat als je list handle niet gevonden is, dat hij alles terug geeft. Kun je checken of je handle mijnlijst is en niet bijvoorbeeld mijnLijst?

**Comment by studiocodeur** [comment]
Ik gebruik topmenuHdm als list handle

![Screenshot 2021-01-07 at 15 50 17](https://user-images.githubusercontent.com/24894030/103906377-1f2fac80-5100-11eb-805a-772f3fda6dbc.png)

Als ik deze  run

```
 listItems(list: "topmenuHdm", level: 1) {
    title,
  }
```

krijg ik

```
{
  "data": {
    "listItems": []
  }
}
```
met deze 

```
 listItems(list: "topmenuHdm_list", level: 1) {
    title,
  }
```
krijg ik alles te zien

**Comment by KevinBeckers** [comment]
Zijn je list items ingeschakeld?

**Comment by studiocodeur** [comment]
Ah! Gevonden!
Lijkt dan wel voor elke site beschikbaar te zijn. 

Ik kan de items alleen maar global enablen.
Maar lijkt wel te werken!

`query MyQuery {
  listItems(list: "topmenuHdm") {
    title
    children {
      title
      ... on topmenuHdm_List {
        title
        headerTitleNl
        headerTitleEn
        children {
          title
          ... on topmenuHdm_List {
            title
            headerTitleNl
            headerTitleEn
          }
        }
      }
    }
  }
}
`

**Comment by studiocodeur** [comment]
Deze lijkt te werken!

`query MyQuery {
  listItems(list: "topmenuHdm") {
    title
    children {
      title
      ... on topmenuHdm_List {
        title
        headerTitleNl
        headerTitleEn
        children {
          title
          ... on topmenuHdm_List {
            title
            headerTitleNl
            headerTitleEn
          }
        }
      }
    }
  }
}
`

**Comment by KevinBeckers** [comment]
Oke super! Per site moet inderdaad nog gemaakt worden. We hopen daar binnenkort aan toe te komen.
