### ISSUE TITLE
Support for CraftQL? 

### ISSUE THREAD

**Issue by ardian-c** [dutchheight/craft-navie#4]
Hi, 

I tried using the plugin and it works fine with built in GraphQL editor, however when used with CraftQL plugin it does not recognize the schema. Is there a way around to use it with CraftQL?

**Comment by freimutt** [comment]
Hi Ardian,

Unfortunately, we still have to implement the use of CraftQL. 
You can use this in the next release.

**Comment by freimutt** [comment]
#5 Could you update to the latest version (1.2.0).
