### ISSUE TITLE
Multisite content doesn show up in Navie

### ISSUE THREAD

**Issue by lexislav** [dutchheight/craft-navie#7]
It seems that Navie shows entries for primary site only.

Scenario: I have Multisite with few domains: company.com, product.com etc.
When adjusting< Main nav list for product.com domain in navie, only entries for company.com are shown (channels, pages, and structures). But I have also some entry types used only on product.com. THose are not shown in Navie.

Might be related to Craft 3.4 as well.

**Comment by freimutt** [comment]
Could you try out the latest version, let me know if it fixed your issue.

**Comment by lexislav** [comment]
Yes, the problem is solved with latest Navie update. Thanks!
