### ISSUE TITLE
error on getting list items in template

### ISSUE THREAD

**Issue by lexislav** [dutchheight/craft-navie#9]
Using `craft.navie.items().list('mainMenu').all()` ends up with _Impossible to invoke a method ("level") on an array_ message.

Getting the results in this way is possible using level() `craft.navie.items().list('mainMenu').level(1)`.

**Edit:** Craft 3.4.X, Navie 1.2.2.1

**Comment by freimutt** [comment]
Could you provide more information about your setup. I cannot reproduce your issue.

**Comment by lexislav** [comment]
Sorry, It was my mistake in template. It works as it should.
